language: java

sudo: false

addons:
  sonarcloud:
    organization: "wadge"
    token:
      secure: "yeRo6vypao4CdYHakULvSYDP8jR5w8zhmfFhJn/epcizIlRdlkZbvLTNw6yLjv2GUPFmWE/ejI6Uelb1BNPJjx8Yy+50Xr0VpKVq2jF3/eVdDNTLbkAuUATQy269id6Gl+ID/h3FDPlQG4xZjoCm/LBjyzRJdWN4QKdrxJIjBXfyvWn5eUxcNWwf5W45VBBcA6lIfEw9O/xIWAflbUZ8R7sg4TPPS76Z3OZmYBfJgcIIKsYZV+wK9tOC1VNsNT8f8uoH1S/Abvq+CnVVTFzMnxesTcczaLMqxz6xwhxKHwEOC4jUfRMIUNCP9r7FMk1fVgsh3bc3or0hvNuQV+t5XFQPCv69hr/Mu9bNvLlKoj0HENwU2S4MZNFkT+Q3FrCppBQQ6CsW1K4YsytL4ikKUknie1HfZZ12q8qIy8tAV50Fny343gW9UHIsLDWB48gJ/Hzw9VrTJlOzfnzt6qv6IFY8KyE7TqKnnpqvbxTioMOgPlTcmsPlQRyxYK739EOyAQ/7ujpUmdgBwjxerXoumDg5DFg1alZ94x7ApJayEZYh7PA0BtflU9fPNkspcZrvaf6yay2gwv6Is7gcz9jNDBzYdVmcGtfjuxtAlDQ861ue1GYMKzUyYs/ECL7VlQ68oaQvOR1VclAPC600+g/Q114abZebFkQKtGsJ4ogEnXg="

before_install:
  - chmod a+x ./gradlew
script:
  - ./gradlew --version
  - ./gradlew check 
  - ./gradlew sonarqube --debug


after_success:

cache:
  directories:
