language: java

sudo: false

addons:
  sonarcloud:
    organization: "wadge"
    token:
      secure: "hPd3bt1bCrKw0Ilq9XmVvitjExxzN7vC6xRreqIyq30EyYMGU468qbLPPKiW6T5eUFnfDxN9ipNFm4wSeGKSL8PX720TvwjmIaJWgVucv9GHUM7sojOBQssGKpQ2s+VXFFkIIUOx/t5wbzWpGe+rrSC71u3mwWHGgglnBudJB6LrlASOgTUPKzSUI1cwXVXZFYKLLtIAEOOtxc6HaiZwIWalZdQfI50gsfozR7Jc2AoTKQqR64XgYFRv8seDfFqM5jTuzN31UwB5ILOWPZ8RZSoIsi3EJMWOOleVLFc5uu3Vxz8R62iXwu6SvOWiDSA+JNavWfKDvWY92Lb/6rxB/1C+6RD1m9NXb6ODkEyTTWijReDKYRNtlsUwbOX71ezFC9dEyJCuGZAb7TJ/x4i8ZZrhoVkhnSQ95taHwRqbU9NZ+478tLV4YVvouUMYF+0YmD/DE7zSj2q0Qw6tldy8KWXgFUZjICkZO+9zar6Oxl6sjClw9uujsAe9NHEhlGB2EhZTNUe8khcOyTE0PjZPHbbGyATQhtMtLsXr0MPw8XPB+pGJzrxWx7slYRVMrmQlMuzER3rqVwTMjco4xT+fpkux5oPViKIBCPP6VpZkQW+1/DqnPsFAkeX2uXOVLLz7pJ0haRQ8++UX5CrZDc04SOolM/3YVRv4QtjlIanFdi8="

before_install:
  - chmod a+x ./gradlew
script:
  - ./gradlew --version
  - ./gradlew check 
  - sonar-scanner
  - ./gradlew jacocoTestReport coveralls
  # - ./gradlew sonarqube
  - ./gradlew asciidoctor

before_deploy:
- export VERSION=`./gradlew -q version`
- export DOCDIR="build/docs"
- export DOCFILE="doc"
- mv "${DOCDIR}/{DOCFILE}.pdf" "${DOCDIR}/${DOCFILE}-${VERSION}.pdf"
- export TRAVIS_TAG=v${VERSION}
- export DOCUMENTATION="${DOCDIR}/${DOCFILE}-${VERSION}.pdf"
- echo documentation is {DOCUMENTATION}

deploy:
- provider: releases
    api_key:
      secure: "cTnQ2d+sWDavvmZRH5ccdpGXTkjdHB3m9orkdbzqwW7gtWC7p0UliqTAbAOPC/y4xUUYkJFi6LgwtBvaMvpYk2hz483w3GNe/bL2+kqiCLaMFyCz48HRLJxwahr6TMCX5n7yRSyYDBziydZBSUcR86BtVrs0CKAly1EeMABcEVQsuyh8QwY4Hl+WAywGnngnWa88n6FvWsaqhHQ9g4xWF4St7H+oupuzjiDC9guFG+leJchbHxq0kusDmUYidHfdMIEuJLmdFnn1wTW/X1Oy6ntieRGIF/mLHLXRIn82xfU4QjVzK+VYGo2dar3wti8/7ZgNPKFqz2f/IiHtIYaOODwfMn/kdx7xdYhTJiYg07D+8ba7Vf+fCnSyJcGrbXuIfYOvhfQQK6y0GJPvNKIjMGryB0V6eyGfb/ePQvYwzG+lEhVJm5hzOoEqCCP9s7lo2o25mRZ/T++tzKG2ohq2cQjZcyA26FH0j3/f4mn/E2+Thc6UxZ/cOwXW9H9gh5wa1MarUmeMjm/Cl+AenVTx78SHWyVEJQNBlSoQiZw/w5dhYPxsrJXhduYSfzQYdKs2ERnUJdp/76DJkEX7Uwav+bzCoP5mfKpt0vT3EQtnZTBxyUNHETgCoF0YCfamm6uK6QnTJQRWmO0naUts+g6HV/y8XtS08JdwBcLLPdxwQUA="
    file:
      - ${DOCUMENTATION}
    skip_cleanup: true
    overwrite: true
    draft: true
    on:
      branch: master
      tags: false
    name: $TRAVIS_TAG

after_success:

cache:
  directories:


