language: java

sudo: false

addons:
  sonarcloud:
    organization: "wadge"
    token:
      secure: "ETI1hfScpdYVyUJbf7WWlaziKc/LAD4+wtXwhX2WTFq9pqFw6t14Fd4mt4OCsYYeOd5/WqTB08dNoEw9INVYoy7vI9kMRTlkKgstiz5AHWBheRk3u23iDXxE8ZrbPCXr99wP5aUpF4zp/HIays7WZRjkh2Y9NcDUQa8cHcC4moNNZDc6L03UMKmH1DNvwQuh8FvW+gHRI+ienAWVGKk1g2GaR8RJVZMZu0sLI5BTTH40WtOaR+Lvz9EXd+s/SUYWludWk5bJWoqQhT6vnptTxUbFBjLi/dQLF/D1J/jalfnl09lFr9PEmbzWvBNq8Em0Nl2ytR/mNPRHbG5CCeTmi8NLSbFrfKBWSQe5rImxS3e3o4WGRvFAZn6aH0WoVYK0edx5ieB7yleDIl5r+lV9j2RWXI/YYN7PD6E3enNbBU3vISxsonic62MYFdPyTVmoQ1iqV9DayvBfH4klwvMJYgciQdnbj+5Qh5ouGWNcRdS8b/kvYgbXy6FCqX9JOvX0aVXy3UZkNSYMCsJFT/pCzi6vQiUtPhflBqaGxzQB2e2V+dwEHDocx/VQ/tFc2TfUy+8EIq8I5GitRNHLKXO+8QJ+Nh1NogUpJbCX4CC/SVsuDeAS0s8xXyZKybKbIsSYgTQnysPoalne0O3Zi5O8rvcRMKGhKw9wcuyz2zPBR8E="

before_install:
  - chmod a+x ./gradlew
script:
  - ./gradlew --version
  - ./gradlew check 
  - ./gradlew sonarqube


after_success:

cache:
  directories:
