language: java

sudo: false

addons:
  sonarcloud:
    organization: "wadge"
    token:
      secure: "P209y+njLr7gSr9DQCVhlAaPgldWqdxe0Ti5kIPUPVBrkABCoFNYuo3CXInoLjdQ+xnaSPEt6l7m4+j2bilbdnT/vbWBhrg0AEhy5e1jCMJU2E3D2aC2j16j8pBTjHZhHi+KNnz2XAxAzdRnc2Kqza+CeKKNQVqn5gNlNB0Kutscmk2oCvUun5cJ1RssXpX2eb6XYvRlEu9/8BTxNdewV31hIGUDyswnIlj0wwVOw4/FVOjs8sfin+KyRq+J/TnqOfBL+JsD2/aXVSfoewziP6L5lnQDjACQGF6I4Zr5v/n4s7zWKq8wBwmTV2qGuR1OaJBSbJgLp0PwaQ8xSo0Ks+BxYEqYQWwkLE3YrO2OBbsdVtvlJnNrhOKrGeW4wTEJW2eLUANPbEVjF77apWFK/rzX0JAhcuXf/q/i6jbr0ZBok2CZumckkjel0Zal2ywv+vECgYdMaMqgx1XuJ8QktNa2UmQYsz75AXxAt2o/ajO+jMDcFdMrU7YAAZFuOj2Z5t18OZaLTkaAiYyLJLKDnrQIMYKVtsh9ZlgA/H53DcWprQlrCss8gVcTBWDFXO5xef1N+uNvxNJ5rWKaTEdX9IG8LBKfvVjYVwS5qkmRM/80VLPtidVANtHrN/BKYgFHZ97D1MU4RWqk/lI2IgtqXbdG/KpUhuAnOSakLDRo0jI="
before_install:
  - chmod a+x ./gradlew
script:
  - ./gradlew --version
  - ./gradlew check 
  - ./gradlew sonarqube


after_success:

cache:
  directories:
