language: java

sudo: false

addons:
  sonarcloud:
    organization: "wadge"
    token:
      secure: "0IGKx47Qz3y7nFw6c3Z39d0n6mleC6ZT3mqOlxaOPhxQmmWsJVI9dzcsv7U+/oG9dlLluktqJOawpIcbjoTWntchucRMp2Tw96DPBb+VuKDm2Sn4Y+e+ByQC2H3B30pnlqw4FGRgOV5z8doj2BHCl9sa8ODMYL7833dVOlfSameavOjGep1i9gFSvr3k1cES4nKYA5v1zew1FYoxP0U9EsbFfSuVPWi/F8rgjpZP1REWv6SQrsShSbfMQgjWmYQNmqqN+93bS0f0SEIVRPh9ODWMMBzn/Nk2t2jqYEHeCFWd1/GIXFDgZEycE/zrPJCDSfDdN1cspIS4ou7Vikm6m/7wqv5tZo7KStxC7VAFSv1w3E6sKwkuDd809Ixyl50af6G6P4zyE3hapYBax5hKtIuxRkDdxGlFRDg/S1rH+kFlhVAIddxdiMFb+zoRrfCDQuwCG2INwRqRPwtHWnQ/diRXbvPBQrXkbRWJewucJ4KySPiq22mXm2uPF7KvWV48pVKa7pX2x7BuAgy2f5IctTyBfPuVtEDfE9M1N6OUq24ZX4d744VNeOFBJGcCCFuecFh3/3dMSN1CgPIdZXabui6++cbS+2lo2/N7bY79PoQzZSXIzrovDbSWd2RIGMjb8X3KdjLY1yAnD2aHzdeDu30kLkxyLJfbbJw2X8jCowU="


before_install:
  - chmod a+x ./gradlew
script:
  - ./gradlew --version
  - ./gradlew check 
  - ./gradlew sonarqube


after_success:

cache:
  directories:
