language: java

sudo: false

addons:
  sonarcloud:
    organization: "wadge"
    token:
      secure: "rpTKCQGpm9GmwMKPa93fkpJ70u0itrMUzE8X9pS/N9kB8586BosDKa5lLWZFHFPa3uVgx7p9cmJG98xuBnniNN9VrJid99NNjvzdJSpJ6km8ePiqoO3IFzqFH4X1fl1TSCQl0triqmiKfg66Cs9uUO3n4ysS6iy9h3lIwBEWjdX2YydoP1nE9Xl1UxphiO/fDDuSkqUh2zbhWuIxdJyyoA/3JSks/3ISJ1C+Gc/W1ljOLAuGKuIQ5ul34t7l0iBDiUKLANRGIPI/T66F0lU3mJo4NjVoYyn2u19QhTOl5GrMs+r+FSQLBLRleWFeAeZxKTUHmWFfEwFW7y7T514kiWBbBwGF/M+ANZMwvahClne8v4T7qBAF53ZLlHWyqRvg3QDHhvnBEPM5qvkVJJ1MOO4soYNYzVt+tAuO5Bne/+HLUNINHrNpnxJ/nut4aT5v3jEYlRSmT7JVV2sg9LDTmsawBR7PGjSGzmOoECn0Ik8/B1MUf4+70qLTywSqbssW1gErTLYEenj9haTFDrmm6rvueqE5b0IlFhGOHt3A1IHYVZcOsSzdrDX0HStDys2zbvPZYfKFNofn/sGyvpoxyc7JVgu2GdbR/q/X9n40zmjjMkFQFdYs6j/gx64qMITQy5dU+6q0LCqAhol+fMdF++kno0iHdQY9oH2Qd6G0sfY="
before_install:
  - chmod a+x ./gradlew
script:
  - ./gradlew --version
  - ./gradlew check 
  - ./gradlew sonarqube


after_success:

cache:
  directories:
