language: java

sudo: false

addons:
  sonarcloud:
    organization: "wadge"
    token:
      secure: "oW8fiJLqrmH7Sw5rbF4dISNggrMVz1EbDDA7paJPmThvP9IEDASt/MQoioB5NlUMXyVtzZt0EuwL47HU9/ev96SRIeplOhulT/eC6KXGSpqRKJbMf7y/2fu4mrklcTFUOd1aC69VTHmTT+aReik3Aqnksu06UU5dteCFg1vksaO7l0OTIxIg0E0jvThLJPtB1MYnFrKix/MqY7mmUCm1Wh2RrDAw9fOqKQap6N1yrjdHmaiDboGlcDVshvmAU6vn4v36t4X0UACB2VHJmXUf6+ri6utoq7wPmQTUloi8r41tyX9uGlUma9pQGEIlzj0ZdvwAWveJvxQqHGQbZoCEC1vcRyLNnwIKJkdHc9tcjPWk1P3MqpH1etesV6LDNNTUl17v2A3rqjY4mKUSYUT6nLfh0Kq03sUCDBn4BvlljAczMW6XHdJeSRQc3ykTqF31Qz/6HZlrmNy+XdUL5LSzk0g8ufcVtPm5jO9J9o+lfavY/8MKuVbJJ7Qvoo2e/6wh9noGVf4E+T6NCfzJp3UcicSmwM6I5bC07aBA0JEio1a/aJDkJKE5JPR8lS2kB/IiVOxXM6wgq8Icz7gygX8OM+tzprnkUoY4E/mEXRhR9BtKhpIaap9AfJAIh/jOmDTVlmgQAOTH9bOXVEMbdMdkkwRIB8z6pfHySXlKmV8RLcI="
before_install:
  - chmod a+x ./gradlew
script:
  - ./gradlew --version
  - ./gradlew check 
  - ./gradlew sonarqube


after_success:

cache:
  directories:
