@startuml Add to fridge
autonumber
actor Utilisateur
Utilisateur -> Front: Clique sur l'onglet "Ajout au frigo"
Front -> "FridgeController::addToFridge": Demande le contenu du frigo
"FridgeController::addToFridge" -> "Fridge::addToFridge": Récupère le contenu
"Fridge::addToFridge" -> "FridgeController::addToFridge"
"FridgeController::addToFridge"-> Front: Envoie du résultat de la requête
Front -> Utilisateur: Redirection vers le frigo
@enduml