@startuml addToFridge
    !include ../style/commons.style

    participant ": Front" as ft
    participant ": Back" as bk
    participant ": FridgeController" as fc

    activate ft
    ft -> bk: POST /fridge/addition
    activate bk
    bk -> fc: addToFridge(foodList)
    activate fc
    create "FridgeController.fridgeService: FridgeService" as f
    fc -> f: FridgeService(FridgeDao)
    activate f
    fc -> f: addToFridge(food)
    f --> fc
    fc --> bk
    bk --> ft
    deactivate f
    deactivate bk

@enduml