@startuml monthFilterDays
    !include ../style/commons.style

    participant ": Front" as ft
    participant ": Back" as bk
    participant ": FoodController" as fc

    activate ft
    ft -> bk: GET /foods/{month}/days
    activate bk
    bk -> fc: getFoodFromMonth(month)
    activate fc
    create "FoodController.foodService: FoodService" as fs
    fc -> fs: FoodService(foodDao)
    activate fs
    fc --> fs: getFoodFromGivenMonth(month)
    fs --> fc
    fc --> fs: sortByDays(food)
    fs --> fc
    deactivate fs
    fc --> bk
    bk --> ft
    deactivate bk
    ft <-- ft: Traiter les données reçues

@enduml