@startuml monthFilterSystem
    !include ../style/commons.style

    actor User
    autonumber

    participant ": Front" as frontend
    participant ": Back" as backend

    User -> frontend: cliquer sur mois X
    activate frontend
    frontend -> backend: GET /foods/{X}
    activate backend
    backend --> frontend: liste des légumes du mois X
    User <-- frontend: afficher liste des légumes du mois X
    User -> frontend: cliquer sur un légume Y
    User <-- frontend: afficher informations du légume Y
    User -> frontend: cliquer sur le switch "Trier par jours"
    frontend -> backend: GET /foods/{X}/days
    backend --> frontend: liste des légumes du mois X
    User <-- frontend: afficher liste triée des légumes du mois X 
    deactivate frontend
    
@enduml