@startuml recipesFridge
    !include ../style/commons.style

    participant ": Front" as ft
    participant ": Back" as bk
    participant ": RecipeController" as rc

    activate ft
    ft -> bk : POST /recipes/fridge
    activate bk
    bk -> rc : getAllRecipes()
    activate rc
    create "RecipeController.recipeService: RecipeService" as rs
    rc -> rs : RecipeService(recipeDao)
    activate rs
    rc -> rs : getAllRecipesUsingFridge()
    rs --> rc
    deactivate rs
    rc --> bk
    deactivate rc
    bk --> ft
    deactivate bk
    ft <-- ft: Traiter les données reçues

@enduml