@startuml recipesSystem
    !include ../style/commons.style

    autonumber
    actor User
    participant ": Front" as frontend
    participant ": Back" as backend

    User -> frontend: cliquer sur "Recettes"
    User -> frontend: selectionner filtrage " recettes favorites"
    activate frontend
    frontend -> backend: GET /favoriteRecipes
    activate backend
    backend --> frontend: liste  des recettes favorites
    deactivate backend
    frontend --> User: afficher la liste des recettes favorites

    deactivate frontend

@endum
