@startuml recipesSystem
    !include ../style/commons.style

    autonumber
    actor User
    participant ": Front" as frontend
    participant ": Back" as backend

    User -> frontend: cliquer sur "Recettes"
    User -> frontend: selectionner "Recettes Realisées"
    activate frontend
    frontend -> backend: GET /doneRecipes
    activate backend
    backend --> frontend: liste  des recettes realisées
    deactivate backend
    frontend --> User: afficher la liste des recettes relisées
    deactivate frontend

@endum
