@startuml
autonumber
actor User
User -> Front: Demande la liste des aliments dans son frigo
Front -> Back: Requête de la liste des aliments
Back -> "getExpirationAlert()": Requête de la liste des aliments actuellement dans le frigo
"readFridge()"-> Back: Retourne un Json
Back -> Front: Réponse Json
Front -> User: Affichage
@enduml