@startuml 
autonumber
actor User
participant ": Front" as frontend
participant ": Back" as backend

User -> frontend: cliquer sur "Cartes des magasins"
activate frontend
frontend ->backend:GET /map/lat/lng
deactivate frontend
activate backend
backend-->frontend: réponse affichage de la map
deactivate backend
activate frontend
frontend --> User: afficher map de la liste des magasins
deactivate frontend
@enduml