@startuml
autonumber
actor User
User -> Front: Demande liste péremptions à une date donnée
Front -> Back: Requête de la liste des péremptions à cette date
Back -> "getExpirationAlert()": Requête de la liste des péremptions à la date donnée
"getExpirationAlert()"-> Back: Retourne un Json
Back -> Front: Réponse Json
Front -> User: Affichage
@enduml