@startuml
autonumber
actor User
participant ": Front" as frontend
participant ": Back" as backend

 
User -> frontend: cliquer sur "Recettes"
activate frontend
frontend -> backend: GET /recipes
deactivate frontend
activate backend
backend --> frontend: liste  des recettes
deactivate backend
activate frontend
frontend --> User: afficher la liste des recettes

deactivate frontend
 
 
@endum
