@startuml updateFridgeSystem
    !include ../style/commons.style

    actor User
    autonumber

    participant ": Front" as frontend
    participant ": Back" as backend

    User -> frontend: cliquer sur "Frigo"
    activate frontend
    frontend -> backend: GET /fridge
    activate backend
    backend --> frontend: liste des légumes du frigo
    User <-- frontend: afficher liste des légumes du frigo
    User -> frontend: cliquer sur le bouton "+"" d'un aliment
    User -> frontend: appuyer sur le bouton "Prendre les aliments"
    front -> backend: POST /fridge/update
    backend --> frontend
    frontend --> User: mettre à jour le frigo
    deactivate frontend

@enduml