= Wadge-BackEnd
Doc Writer <project.wadge@gmail.com>

Beaucoup de personnes ne portent pas une grande attention à ce qu’elles achètent et se retrouvent avec des aliments périmés. Elles doivent donc les jeter. Certaines mangent systématiquement la même chose et seraient contentes de découvrir de nouvelles recettes.
D’autant plus s’ils ont déjà tous les aliments nécessaires chez eux. D’autres encore souhaitent consommer les aliments de saison pour ne pas faire importer de produits.

Nous avons créer une application pour gérer divers aspect de l’univers culinaire. Le gachis alimentaire est adressé au travers d’un suivi des dates de péremption des produits que l’on possède chez soi. Les nombreuses importations de produits sont limitées par la mise en évidence des fruits et légumes de saison directement dans des recettes associées.

Wadge est une application composée en deux parties. La première, Wadge-BackEnd correspond au code métier Java qui a pour but de gérer toutes requêtes ( création du frigo, modifier le frigo, lire et afficher les aliments ). Tandis que Wadge-FrontEnd à pour objectif de simplifier l'interaction entre le BackEnd et l'utilisateur.

NavBar plus simple. 

== Routes
[cols="h,5a"]
|===
| URL
| /food_list
| Method
| GET
| Response Body
| [...
    {
        "nom": "mandarine",
        "type": "fruit",
        "consommation": ["janvier", "fevrier", "octobre", "novembre", "decembre"]
    }...
]
|===

[cols="h,5a"]
|===
| URL
| /map/{lat}/{lng}
| Method
| GET
| Response Body
|{"candidates":[{"formatted_address":"58 Rue du Général de Gaulle, 95880 Enghien-les-Bains, France","opening_hours":{"open_now":true},"location":{"lng":2.3052543,"lat":48.9695271}}]}
|===

[cols="h,5a"]
|===
| URL
| /filter/{month}
| Method
| GET
| Response Body
| [
    {
        "type": "legume",
        "nom": "ail"
    }...
]
|===

[cols="h,5a"]
|===
| URL
| /alerts
| Method
| GET
| Response Body
| 
    {
        "TWO_DAYS":[
            {"dateAjout":"01/11/2020","quantite":"24","nom":"poire"},{"dateAjout":"10/10/2020","quantite":"2","nom":"poireau"}
        ], 
        "FIVE_DAYS":[], 
        "EXPIRED":[
            {"dateAjout":"10/10/2020","quatite":"2","nom":"poire"},{"dateAjout":"01/11/2020","quantite":"12","nom":"poireau"}
        ], ...
    }
|===

[cols="h,5a"]
|===
| URL
| /alert/{type}
| Method
| GET
| Response Body
| 
    [
        {"dateAjout":"01/11/2020","quantite":"24","nom":"poire"},{"dateAjout":"10/10/2020","quantite":"2","nom":"poireau"},
        ...
    ]
|===



== Diagramme de classe

Les classes dans le BackEnd sont dispatcher dans les packages.
Le package Fridge aura pour but de gérer les requetes liées au Frigo de l'utilisateur (le créer, le modifier...).
Les classes Foods et FridgeFood nous permettent de raccourcir les listes utilisées. Pour chaque fruits & légumes nous créons un objet Food.
Nous avons aussi 3 controleurs. Chacun gérant une partie de l'application.

image::./diagram/out/Wadge-BackEnd.svg[]
== Différents diagrammes de séquences
=== Carte
image::./diagram/out/SequenceDiagramMap.svg[]
=== Liste des aliments en fonction d'un mois donné
image::./diagram/out/SequenceDiagramFilter.svg[]
=== Liste des aliments avec leur mois de consommation
image::./diagram/out/SequenceDiagramFoodList.svg[]
=== Liste des aliments à manger avant une certaine date
image::./diagram/out/SequenceDiagramAlert.svg[]
=== Liste des aliments à manger aux différents dates
image::./diagram/out/SequenceDiagramAlerts.svg[]
=== Liste des recettes
image::./diagram/out/SequenceDiagramRecipes.svg[]
=== Liste des aliments présents dans le frigo
image::./diagram/out/SequenceDiagramFridgeDisplay.svg[]
=== Ajout d'aliments au frigo
image::./diagram/out/SequenceDiagramFridgeAddition.svg[]