@startuml backEnd
    !include ../style/commons.style

    package wadge.google {
        class Search {}
    }

    package wadge.backend {
        class Application {
            + main(args: []string): void <<static>>
        }

        class GoogleController {
            + getCloseShops(lat: double, lng: double): ResponseEntity<JSONObject>
        }
    }

    GoogleController o..> Search

@enduml