@startuml backEnd
    !include ../style/commons.style

    package wadge.google {
        class Search {}
    }

    package wadge.Food {
        class FoodList {}
    }

    package wadge.fridge {
        class Fridge {}
        enum RecallType {}
        class ExpirationRecall {}
        class DataManager {}
    }

    package wadge.recipe {
        class Recipe {}
    }

    package wadge.backend {
        class Application {
            + main(args: []string): void <<static>>
        }

        class HelloController {
            + getCloseShops(lat: double, lng: double): ResponseEntity<JSONObject>
            + getRecipes(): ResponseEntity<List<Map<string, Object>>>
        }

        class FoodController{
            - FOOD_LIST: string <<static final>>
            - foodList: FoodList <<static final>>
            + getFoodList(): List<Food>
            + getFoodFromMonth(month: string): List<Food>
        }

        class FridgeController{
            - FRIDGE_FILE: string <<static final>>
            - fridge: Fridge <<static final>>
            + getFridge(): List<FridgeFood>
            + addToFridge(foodList: string): List<FridgeFood>
            + getExpirationAlerts(): Map<string, List<FridgeFood>>
        }
    }

    HelloController o..> Search
    HelloController *..> Recipe
    FoodController *--> FoodList
    FridgeController *--> Fridge
    FridgeController *..> RecallType
    FridgeController *..> ExpirationRecall
    FridgeController o..> DataManager

@enduml