@startuml google
    package google{

         class Search {
            - KEY: string <<static final>>
            + jsonToFile(fileName: string, json: JSONObject): void
            + request(lat: double, lng: double): JSONObject
            + parseJSON(json: JSONArray): JSONArray
        }
    }
    
@enduml