@startuml
autonumber
actor User
User -> Front: Demande liste aliments
Front -> Back: Requête de la liste aliments
Back -> "readFile()": Requête de la liste aliments
"readFile()"-> Back: Retourne un Json
Back -> Front: Réponse Json
Front -> User: Affichage
@enduml